"use client";
import Navbar from "../components/navbar/Navbar";
import styles from "./globals.module.scss";
import { Monoton } from "next/font/google";
import { Orbitron } from "next/font/google";
import { Space_Grotesk } from "next/font/google";
import React, { useEffect, useRef } from "react";
import { gsap } from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";

export const monoton = Monoton({ subsets: ["latin"], weight: "400" });
export const orbitron = Orbitron({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});
export const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const triggerElement = useRef(null);
  const target = useRef(null);
  useEffect(() => {
    gsap.registerPlugin(ScrollTrigger);
    const tl = gsap.timeline({
      scrollTrigger: {
        trigger: triggerElement.current,
        start: "top top",
        end: "bottom top",
        scrub: 0.5,
      },
    });
    tl.to(triggerElement.current, {
      padding: "0.2rem 0rem",
      zIndex: 50000,
    });
    tl.to(target.current, {
      scale: 0.86,
    });
  });
  return (
    <html lang="en">
      <body className={styles.layout}>
        <div className={styles.navbar} ref={triggerElement}>
          <div className={styles.navContainer} ref={target}>
            <Navbar />
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
