import Page2 from "./Page2";
import styles from "./page.module.scss";
// export const metadata = {
//   title: "Wuild protocol",
//   description: "Generated by create next app",
// };

export default function Page() {
  return (
    <div className={styles.page}>
      <Page2 />
    </div>
  );
}
