import styles from "./page.module.scss";
import Home from "../components/home/Home";
import GamePlay from "@/components/gamePlay/GamePlay";
import Tokens from "@/components/tokens/Tokens";
import RoadMap from "@/components/road map/RoadMap";
import Community from "@/components/community/Community";
import Footer from "@/components/footer/Footer";

export const metadata = {
  title: "Wuild protocol",
  description: "Generated by create next app",
};

export default function Page() {
  return (
    <div className={styles.page}>
      <div className={styles.home}>
        <Home />
      </div>
      <div className={styles.gamePlay}>
        <GamePlay />
      </div>
      <div className={styles.tokens}>
        <Tokens />
      </div>
      <div className={styles.roadMap}>
        <RoadMap />
      </div>
      <div className={styles.community}>
        <Community />
      </div>
      <div className={styles.footer}>
        <Footer />
      </div>
    </div>
  );
}
